CREATE SEQUENCE SEC_USERS
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_SEC_USERS
BEFORE INSERT ON ERP_USERS
FOR EACH ROW
BEGIN
SELECT SEC_USERS.NEXTVAL INTO :NEW.IDUSER FROM DUAL;
END;
/

CREATE SEQUENCE SEC_CUSTOMERS
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_SEC_CUSTOMERS
BEFORE INSERT ON CUSTOMERS
FOR EACH ROW
BEGIN
SELECT SEC_CUSTOMERS.NEXTVAL INTO :NEW.IDCUSTOMER FROM DUAL;
END;
/

CREATE SEQUENCE SEC_LOGS
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_SEC_LOGS
BEFORE INSERT ON LOGS
FOR EACH ROW
BEGIN
SELECT SEC_LOGS.NEXTVAL INTO :NEW.ID_LOG FROM DUAL;
END;
/

CREATE SEQUENCE SEC_ORDERS
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_SEC_ORDERS
BEFORE INSERT ON ORDERS
FOR EACH ROW
BEGIN
SELECT SEC_ORDERS.NEXTVAL INTO :NEW.IDORDER FROM DUAL;
END;
/

CREATE SEQUENCE SEC_ORDERSPRODUCTS
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_SEC_ORDERSPRODUCTS
BEFORE INSERT ON ORDERSPRODUCTS
FOR EACH ROW
BEGIN
SELECT SEC_ORDERSPRODUCTS.NEXTVAL INTO :NEW.IDORDERPRODUCT FROM DUAL;
END;
/

CREATE SEQUENCE SEC_PAY
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_SEC_PAY
BEFORE INSERT ON PAYMENTMETHODS
FOR EACH ROW
BEGIN
SELECT SEC_PAY.NEXTVAL INTO :NEW.IDPAYMENTMETHOD FROM DUAL;
END;
/

CREATE SEQUENCE SEC_PRODUCTS
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_SEC_PRODUCTS
BEFORE INSERT ON PRODUCTS
FOR EACH ROW
BEGIN
SELECT SEC_PRODUCTS.NEXTVAL INTO :NEW.IDPRODUCT FROM DUAL;
END;
/

CREATE SEQUENCE SEC_ROLES
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_SEC_ROLES
BEFORE INSERT ON ROLES
FOR EACH ROW
BEGIN
SELECT SEC_ROLES.NEXTVAL INTO :NEW.ID_ROL FROM DUAL;
END;
/

CREATE SEQUENCE SEC_PERMITS
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_SEC_PERMITS
BEFORE INSERT ON PERMITS
FOR EACH ROW
BEGIN
SELECT SEC_PERMITS.NEXTVAL INTO :NEW.ID_PERMIT FROM DUAL;
END;
/

CREATE SEQUENCE SEC_TYPES
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_SEC_TYPES
BEFORE INSERT ON TYPES
FOR EACH ROW
BEGIN
SELECT SEC_TYPES.NEXTVAL INTO :NEW.ID_TYPE FROM DUAL;
END;
/

CREATE SEQUENCE SEC_COMP
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_SEC_COMP
BEFORE INSERT ON COMPOSITION
FOR EACH ROW
BEGIN
SELECT SEC_COMP.NEXTVAL INTO :NEW.ID_COMP FROM DUAL;
END;
/