--------------------------------------------------------
-- Archivo creado  - lunes-octubre-20-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE CLIENTES 
   (	IDCLIENTE NUMBER, 
	NOMBRE VARCHAR2(30 BYTE), 
	APELLIDO1 VARCHAR2(20 BYTE), 
	APELLIDO2 VARCHAR2(20 BYTE), 
	DIRECCION VARCHAR2(30 BYTE), 
	TELEFONO NUMBER, 
	EMAIL VARCHAR2(30 BYTE), 
	ELIMINADO NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
REM INSERTING into CLIENTES
SET DEFINE OFF;
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,EMAIL,ELIMINADO) values ('1000','Pedro','Perez','Hernan','Prueba 2','123654789','pedroH@gmail.com','0');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,EMAIL,ELIMINADO) values ('1','Julian','Garcia','Perez','Calle Falsa 1','659542156','julian@gmail.com','0');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,EMAIL,ELIMINADO) values ('2','Maria','Lopez','Muñoz','Calle Falsa 2','648521456','maria@hotmail.com','0');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,EMAIL,ELIMINADO) values ('3','Sergio','Martin','Martin','Calle Cazoleta,3','64752156','sandra@gmail.com','0');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,EMAIL,ELIMINADO) values ('4','Jesús','Corral','Plaza','Calle Falsa 4','652123456','jesus@gmail.com','0');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,EMAIL,ELIMINADO) values ('5','Silvia','Pereira','Muñiz','Calle Falsa 5','657894521','silvia@gmail.com','-1');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,EMAIL,ELIMINADO) values ('6','Cristina','Sanchez','Boavista','Calle Falsa 6','650421564','cristina@yahoo.com','-1');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,EMAIL,ELIMINADO) values ('7','Alvaro','Perez','Gila','Avenida 1','123456789','ast@hotmail.es','-1');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,EMAIL,ELIMINADO) values ('10','Marta','Figeroga','Gracia','C/ Prueba 13, 12º E','951236547','Mfigeroga_23@hotmail.com','0');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,EMAIL,ELIMINADO) values ('8','Pepe','Cartago','Martin','C/ Constitucion 4,3ºA','123456789','pepito@mail.com','0');
Insert into CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,EMAIL,ELIMINADO) values ('9','Pedro','Cabrera','Martin-Segoviano','Av. Malagon 12, 1º A','123456789','cabrera@mail.com','0');
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX CLIENTES_PK ON CLIENTES (IDCLIENTE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE CLIENTES ADD CONSTRAINT CLIENTES_PK PRIMARY KEY (IDCLIENTE)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE;
 
  ALTER TABLE CLIENTES MODIFY (IDCLIENTE NOT NULL ENABLE);
 
  ALTER TABLE CLIENTES MODIFY (NOMBRE NOT NULL ENABLE);
 
  ALTER TABLE CLIENTES MODIFY (APELLIDO1 NOT NULL ENABLE);
 
  ALTER TABLE CLIENTES MODIFY (APELLIDO2 NOT NULL ENABLE);
 
  ALTER TABLE CLIENTES MODIFY (DIRECCION NOT NULL ENABLE);
 
  ALTER TABLE CLIENTES MODIFY (ELIMINADO NOT NULL ENABLE);

